/**
 * ══════════════════════════════════════════════════════════════
 *  SECOND BRAIN — Vocabulary Dictionary
 *  second-brain/vocab/vocab.js
 * ══════════════════════════════════════════════════════════════
 *
 *  Terms are pulled from the knowledge wiki (obsidian repo).
 *  Each entry:
 *    term  — the headword (acronym or name)
 *    full  — full expansion (optional)
 *    cat   — category, used for the filter chips
 *    def   — definition (HTML allowed: <strong>, <em>)
 *    wiki  — path to the source wiki page (optional; renders a 📂 link)
 *
 *  To add a term: copy any entry, fill the fields, drop it in window.VOCAB.
 *  `wiki` must point to a page that actually exists in the obsidian repo,
 *  or be omitted (no broken links).
 */

window.VOCAB_WIKI_BASE = 'https://github.com/lucasmasunoacn/obsidian/blob/main/';

const CAT = {
  RISK: 'Finance · Risk & Regulation',
  TRADE: 'Finance · Trading & Execution',
  INFRA: 'Market Infrastructure',
  LLM: 'AI & LLM',
  AGENT: 'Agentic AI & Tooling',
};

window.VOCAB = [

  /* ── Finance · Risk & Regulation ──────────────────────────── */
  { term: 'Capital Markets', full: '資本市場', cat: CAT.RISK,
    def: 'The marketplace where borrowers and lenders transact through the issuance and purchase of securities. Unlike <strong>indirect financing</strong> (via banks), capital markets are <strong>direct financing</strong> — investors supply funds directly to issuers.',
    wiki: 'wiki/concepts/Capital Markets.md' },
  { term: 'Basel III', full: 'Basel III Regulation', cat: CAT.RISK,
    def: 'Internationally unified capital and liquidity requirements for banks. Added capital-quality improvements (CET1), liquidity rules (LCR/NSFR), a leverage ratio, and buffers on top of Basel II.',
    wiki: 'wiki/concepts/Basel III Regulation.md' },
  { term: 'Capital Adequacy Ratio', cat: CAT.RISK,
    def: 'Own Capital ÷ (Credit RWA + Market Risk + Operational Risk) ≥ <strong>8%</strong> for internationally active banks (4% domestic). The core Basel solvency test.',
    wiki: 'wiki/concepts/Basel III Regulation.md' },
  { term: 'CET1', full: 'Common Equity Tier 1', cat: CAT.RISK,
    def: 'The highest-quality capital tier — common shares and retained earnings only. Introduced in Basel III with a 4.5% minimum.',
    wiki: 'wiki/concepts/Basel III Regulation.md' },
  { term: 'Tier 1 Capital', cat: CAT.RISK,
    def: 'Going-concern capital: CET1 plus Additional Tier 1 (AT1, e.g. preferred shares). Basel III minimum 6.0%.',
    wiki: 'wiki/concepts/Basel III Regulation.md' },
  { term: 'Tier 2 Capital', cat: CAT.RISK,
    def: 'Gone-concern (supplementary) capital such as subordinated debt. Counts toward the 8.0% total capital ratio but not toward Tier 1.',
    wiki: 'wiki/concepts/Basel III Regulation.md' },
  { term: 'RWA', full: 'Risk-Weighted Assets', cat: CAT.RISK,
    def: 'Assets scaled by riskiness, forming the denominator of the capital ratio. Aggregates credit, market, and operational risk exposures.',
    wiki: 'wiki/concepts/Basel III Regulation.md' },
  { term: 'TLAC', full: 'Total Loss-Absorbing Capacity', cat: CAT.RISK,
    def: 'An additional requirement on G-SIBs (global systemically important banks) ensuring enough loss-absorbing instruments exist for orderly resolution.',
    wiki: 'wiki/concepts/Basel III Regulation.md' },
  { term: 'LCR', full: 'Liquidity Coverage Ratio', cat: CAT.RISK,
    def: 'HQLA ÷ 30-day net cash outflow ≥ <strong>100%</strong>. Ensures a bank can survive a 30-day liquidity stress. Phased in 60%→100% over 2015–2019.',
    wiki: 'wiki/concepts/Basel III Regulation.md' },
  { term: 'NSFR', full: 'Net Stable Funding Ratio', cat: CAT.RISK,
    def: 'Available Stable Funding ÷ Required Stable Funding ≥ 100%. Targets maturity mismatch — prevents funding long-term assets with unstable short-term debt.',
    wiki: 'wiki/concepts/Basel III Regulation.md' },
  { term: 'HQLA', full: 'High-Quality Liquid Assets', cat: CAT.RISK,
    def: 'Assets that can be sold quickly with little loss. Tiered: Lv1 (cash, central-bank reserves, 0% RW govies) at 100%, Lv2A at 85%, Lv2B at 75%.',
    wiki: 'wiki/concepts/Basel III Regulation.md' },
  { term: 'VaR', full: 'Value at Risk', cat: CAT.RISK,
    def: 'The statistical maximum expected loss at a given confidence level over a holding period. Defined by 3 parameters: observation period, holding period, and confidence level. <em>VaR = z × σ × √days × value</em>.',
    wiki: 'wiki/concepts/Value at Risk.md' },
  { term: 'BPV / GPS / SPV', cat: CAT.RISK,
    def: 'Interest-rate sensitivity measures: <strong>BPV</strong> = parallel shift of the whole yield curve; <strong>GPS</strong> = shift of a single tenor (per-point risk); <strong>SPV</strong> = slope (steepening/flattening) change.',
    wiki: 'wiki/concepts/Value at Risk.md' },
  { term: 'Expected Loss', full: 'EL', cat: CAT.RISK,
    def: '<em>EL = PD × EAD × LGD</em>. The average anticipated credit loss — analogous to a loan-loss provision. Covered by pricing/provisions, not regulatory capital.',
    wiki: 'wiki/concepts/Basel III Regulation.md' },
  { term: 'PD', full: 'Probability of Default', cat: CAT.RISK,
    def: 'The likelihood a counterparty defaults, tied to its internal credit rating. A component of Expected Loss.',
    wiki: 'wiki/concepts/Basel III Regulation.md' },
  { term: 'EAD', full: 'Exposure at Default', cat: CAT.RISK,
    def: 'The outstanding exposure expected at the moment of default. A component of Expected Loss.',
    wiki: 'wiki/concepts/Basel III Regulation.md' },
  { term: 'LGD', full: 'Loss Given Default', cat: CAT.RISK,
    def: 'The fraction lost if default occurs: <em>LGD = 1 − Recovery Rate</em>. Collateral covering 60% → recovery 60% → LGD 40%.',
    wiki: 'wiki/concepts/Basel III Regulation.md' },
  { term: 'Unexpected Loss', full: 'UL', cat: CAT.RISK,
    def: 'The gap between Credit VaR (99th-percentile loss) and Expected Loss. This is what regulatory capital is held against.',
    wiki: 'wiki/concepts/Basel III Regulation.md' },
  { term: 'CVA', full: 'Credit Value Adjustment', cat: CAT.RISK,
    def: 'The present value of expected loss from an OTC derivative counterparty defaulting — the "loan-loss provision for derivatives". Charging CVA to traders deters low-credit counterparties.',
    wiki: 'wiki/concepts/Basel III Regulation.md' },
  { term: 'RAROC', full: 'Risk-Adjusted Return on Capital', cat: CAT.RISK,
    def: '<em>RAROC = (Revenue − Risk Cost) ÷ Economic Capital</em>. Compares business units on risk-adjusted profitability to allocate capital efficiently.',
    wiki: 'wiki/infrastructure/Securities Firm Systems.md' },
  { term: 'Economic Capital', full: 'EC', cat: CAT.RISK,
    def: 'Internally-estimated capital a unit needs to cover its risks (measured via VaR). Allocated as risk limits, then performance is judged by RAROC.',
    wiki: 'wiki/infrastructure/Securities Firm Systems.md' },
  { term: 'Settlement Risk', cat: CAT.RISK,
    def: 'The risk a trade fails to settle due to technical/operational failure — even when both parties are creditworthy. Distinct from credit risk; mitigated by DVP, STP, and JSCC novation.',
    wiki: 'wiki/infrastructure/Securities Firm Systems.md' },

  /* ── Finance · Trading & Execution ────────────────────────── */
  { term: 'Derivatives', full: 'デリバティブ', cat: CAT.TRADE,
    def: 'Instruments for hedging future price risk or speculation — primarily options and swaps, traded mostly OTC. A call/put gives the right to buy/sell at a set price; option buyers have limited downside (premium) and large upside.',
    wiki: 'wiki/concepts/Derivatives.md' },
  { term: 'Algorithmic Trading', full: 'アルゴリズムトレーディング', cat: CAT.TRADE,
    def: 'Automated execution of trades by pre-defined mathematical rules. Manages the core trade-off between <strong>market impact</strong> and <strong>opportunity cost</strong> in institutional equity trading.',
    wiki: 'wiki/concepts/Algorithmic Trading.md' },
  { term: 'Market Impact', cat: CAT.TRADE,
    def: 'The adverse price movement caused by your own order — large sells push the price down. Executing slower reduces impact but raises opportunity cost.',
    wiki: 'wiki/concepts/Algorithmic Trading.md' },
  { term: 'Opportunity Cost', cat: CAT.TRADE,
    def: 'The cost of executing too slowly and missing a favourable price. The counterweight to market impact in execution strategy.',
    wiki: 'wiki/concepts/Algorithmic Trading.md' },
  { term: 'VWAP', full: 'Volume-Weighted Average Price', cat: CAT.TRADE,
    def: 'Σ(Price × Volume) ÷ Σ(Volume) over the day. The most common execution benchmark; algos distribute fills along the historical intraday volume profile. "Beating VWAP" = buying below the day\'s average.',
    wiki: 'wiki/concepts/Algorithmic Trading.md' },
  { term: 'TWAP', full: 'Time-Weighted Average Price', cat: CAT.TRADE,
    def: 'Splits an order uniformly across equal time intervals. Simpler and more predictable than VWAP but ignores volume patterns — good for patient execution in illiquid names.',
    wiki: 'wiki/concepts/Algorithmic Trading.md' },
  { term: 'IS', full: 'Implementation Shortfall', cat: CAT.TRADE,
    def: 'Measures the gap between the <strong>decision price</strong> and the final execution price. Minimizing IS = minimizing true total cost; can front-load execution when prices move against you.',
    wiki: 'wiki/concepts/Algorithmic Trading.md' },
  { term: 'POV', full: 'Participation of Volume', cat: CAT.TRADE,
    def: 'Maintains a constant share of market volume (e.g. 10%). Speeds up when volume spikes, slows when it dries up — reducing predictable, leak-prone patterns.',
    wiki: 'wiki/concepts/Algorithmic Trading.md' },
  { term: 'Iceberg Order', cat: CAT.TRADE,
    def: 'Displays only a small visible slice of a large order; each slice auto-refills as it fills. Conceals true size to avoid front-running and adverse moves.',
    wiki: 'wiki/concepts/Algorithmic Trading.md' },
  { term: 'Facilitation', cat: CAT.TRADE,
    def: 'A securities firm crosses a client trade as counterparty (taking the position itself), then unwinds it via algos with minimal impact — providing immediate liquidity.',
    wiki: 'wiki/concepts/Algorithmic Trading.md' },
  { term: 'SOR', full: 'Smart Order Routing', cat: CAT.TRADE,
    def: 'Automatically scans multiple venues (TSE, SBI Japannext, Chi-X…) and routes/splits orders to the best price, liquidity, and fees in real time.',
    wiki: 'wiki/concepts/Smart Order Routing.md' },
  { term: 'Co-location', cat: CAT.TRADE,
    def: 'Placing execution servers physically beside the exchange matching engine to minimize network latency — a core competitive edge in modern execution.',
    wiki: 'wiki/infrastructure/Tokyo Stock Exchange arrowhead.md' },

  /* ── Market Infrastructure ────────────────────────────────── */
  { term: 'Securities Firm Systems', cat: CAT.INFRA,
    def: 'The 6-system IT architecture of a securities firm: ① Retail Ops ② Order & Execution ③ Reconciliation & Settlement ④ Enterprise Management ⑤ Master Data ⑥ External Connectivity — balancing front-office speed with back-office stability.',
    wiki: 'wiki/infrastructure/Securities Firm Systems.md' },
  { term: 'Front vs. Back Office', cat: CAT.INFRA,
    def: 'Front office = trading (speed + accuracy, low-latency infra). Back office = settlement (stability above all, often mainframe batch). Opposite requirements by design.',
    wiki: 'wiki/infrastructure/Securities Firm Systems.md' },
  { term: 'DVP', full: 'Delivery versus Payment', cat: CAT.INFRA,
    def: 'Securities are delivered if and only if cash is simultaneously received — making delivery and payment atomic and eliminating principal (settlement) risk.',
    wiki: 'wiki/infrastructure/DVP and STP Settlement.md' },
  { term: 'STP', full: 'Straight-Through Processing', cat: CAT.INFRA,
    def: 'Automated end-to-end processing from trade execution to settlement with zero manual touchpoints — every manual step is a potential error, delay, or fraud vector.',
    wiki: 'wiki/infrastructure/DVP and STP Settlement.md' },
  { term: 'Novation', cat: CAT.INFRA,
    def: 'A central counterparty (e.g. JSCC) inserts itself as buyer to every seller and seller to every buyer, so participants face the CCP\'s credit — not each other\'s.',
    wiki: 'wiki/entities/Japan Securities Clearing Corporation.md' },
  { term: 'JPX', full: 'Japan Exchange Group', cat: CAT.INFRA,
    def: 'Japan\'s unified securities exchange operator, formed by the 2013 merger of the Tokyo and Osaka exchanges. Backbone of Japanese wholesale trading.',
    wiki: 'wiki/entities/Japan Exchange Group.md' },
  { term: 'JSCC', full: 'Japan Securities Clearing Corporation', cat: CAT.INFRA,
    def: 'The central counterparty (CCP) for JPX trades — confirms trades, nets exposures, and novates to reduce bilateral credit risk. (Clearing.)',
    wiki: 'wiki/entities/Japan Securities Clearing Corporation.md' },
  { term: 'JASDEC', full: 'Japan Securities Depository Center (ほふり)', cat: CAT.INFRA,
    def: 'Japan\'s central securities depository — holds securities in dematerialized book-entry form and runs the final settlement stage. (Custody & settlement.)',
    wiki: 'wiki/entities/Japan Securities Depository Center.md' },
  { term: 'TSE arrowhead', cat: CAT.INFRA,
    def: 'JPX\'s next-gen trading system (2010). Cut order processing from 3 seconds to <strong>10 ms</strong> and grew quote capacity ~13.5× (600→8,200 ticks/s), enabling co-location and modern algo trading.',
    wiki: 'wiki/infrastructure/Tokyo Stock Exchange arrowhead.md' },

  /* ── AI & LLM ─────────────────────────────────────────────── */
  { term: 'Software 3.0', cat: CAT.LLM,
    def: 'Karpathy\'s third computing paradigm: natural-language intent as the interface and the LLM as runtime — vs Software 1.0 (explicit code) and 2.0 (trained weights). "The hot new programming language is English."',
    wiki: 'wiki/concepts/Software 3.0.md' },
  { term: 'Transformer', cat: CAT.LLM,
    def: 'The foundational LLM architecture (Vaswani et al., 2017). Uses <strong>self-attention</strong> to process whole sequences in parallel, capturing long-range dependencies far more efficiently than RNNs.',
    wiki: 'wiki/concepts/Transformer Architecture.md' },
  { term: 'Self-Attention', cat: CAT.LLM,
    def: 'A mechanism where each token attends to all others in one step: <em>Attention(Q,K,V) = softmax(QKᵀ/√d_k)·V</em>. Fully parallel — the key to scaling on GPUs/TPUs.',
    wiki: 'wiki/concepts/Transformer Architecture.md' },
  { term: 'KV Caching', full: 'Key-Value Caching', cat: CAT.LLM,
    def: 'Stores the Key/Value matrices of prior tokens so each generation step only processes the new token — trading memory for speed. Without it, attention cost grows quadratically (O(n²)).',
    wiki: 'wiki/concepts/KV Caching.md' },
  { term: 'GQA / MQA', full: 'Grouped / Multi-Query Attention', cat: CAT.LLM,
    def: 'Shrink the KV cache by sharing Key/Value heads across query heads — a key technique behind efficient long-context models.',
    wiki: 'wiki/concepts/KV Caching.md' },
  { term: 'Context Window', cat: CAT.LLM,
    def: 'The amount of information an LLM can "see" at once (its working memory). Larger windows cost exponentially more, so optimization keeps the active context lean.',
    wiki: 'wiki/concepts/Context Window Optimization.md' },
  { term: 'The Dumb Zone', cat: CAT.LLM,
    def: 'The observed drop in instruction-following once a context window fills beyond ~40–50%. Motivates active context curation (Factor 5 of 12-Factor Agents).',
    wiki: 'wiki/concepts/Context Window Optimization.md' },
  { term: 'Prompt Caching', cat: CAT.LLM,
    def: 'Caching an expensive, repeated prompt prefix (e.g. a system prompt) so it isn\'t re-processed each call — cutting latency and cost by >80% on repeated requests.',
    wiki: 'wiki/concepts/KV Caching.md' },
  { term: 'Chinchilla Scaling Laws', cat: CAT.LLM,
    def: 'Compute-optimal training uses ~20 training tokens per parameter (a 7B model ≈ 140B tokens). Guides the balance between model size and data.',
    wiki: 'wiki/concepts/Transformer Architecture.md' },
  { term: 'MoE', full: 'Mixture-of-Experts', cat: CAT.LLM,
    def: 'An architecture that routes each token to a small subset of "expert" feed-forward layers, keeping per-token compute constant even as total parameters grow massively (GPT-4, Mixtral, DeepSeek).' },
  { term: 'RAG', full: 'Retrieval-Augmented Generation', cat: CAT.LLM,
    def: 'Augments an LLM by retrieving relevant text (usually via vector similarity) at query time. Re-synthesizes on every query — contrast with a compiled LLM Wiki.',
    wiki: 'wiki/concepts/GraphRAG.md' },
  { term: 'GraphRAG', cat: CAT.LLM,
    def: 'RAG that first builds a knowledge graph + community summaries over the data, enabling multi-hop relational reasoning rather than pure semantic similarity (Microsoft).',
    wiki: 'wiki/concepts/GraphRAG.md' },
  { term: "Karpathy's LLM Wiki", cat: CAT.LLM,
    def: 'An architecture where the LLM incrementally compiles and maintains a knowledge base — paying synthesis cost once (like compiled code) vs RAG re-synthesizing per query. Organized by type, not domain.',
    wiki: 'wiki/concepts/Software 3.0.md' },

  /* ── Agentic AI & Tooling ─────────────────────────────────── */
  { term: 'Agentic AI', cat: CAT.AGENT,
    def: 'LLMs used as agents (not just chatbots) that use tools, maintain state, and complete multi-step tasks autonomously. Reliability is the central engineering challenge.' },
  { term: '12-Factor Agents', cat: CAT.AGENT,
    def: 'Cloud-native engineering principles for production-reliable agents (own your prompts/control flow/context; structured outputs; HITL; stateless reducer) — addressing the demo-to-production "reliability gap".',
    wiki: 'wiki/concepts/12-Factor Agents.md' },
  { term: 'Vibe Coding', cat: CAT.AGENT,
    def: 'Karpathy\'s paradigm where the developer gives high-level natural-language intent ("the vibe") and the AI handles implementation. Human directs, reviews, and redirects rather than writing line-by-line.',
    wiki: 'wiki/concepts/Vibe Coding.md' },
  { term: 'HITL', full: 'Human-in-the-Loop', cat: CAT.AGENT,
    def: 'Designing humans into an automated process so the agent pauses for approval at edge cases or high-risk/irreversible actions. In 12-Factor terms, "ask a human" is a standard tool call.',
    wiki: 'wiki/concepts/Human-in-the-loop.md' },
  { term: 'Claude Code CLI', cat: CAT.AGENT,
    def: 'Anthropic\'s agentic command-line tool — a "self-driving" engineer that plans, executes, and self-corrects in a local repo via a Read-Eval-Print Loop, MCP integrations, and CLAUDE.md memory.',
    wiki: 'wiki/concepts/Claude Code CLI.md' },
  { term: 'Agentic Loop (REPL)', full: 'Read-Eval-Print Loop', cat: CAT.AGENT,
    def: 'The autonomous cycle: Plan → Execute (tool call) → Observe → Decide (loop or finish) → human Review. Can run many iterations per prompt.',
    wiki: 'wiki/concepts/Claude Code CLI.md' },
  { term: 'MCP', full: 'Model Context Protocol', cat: CAT.AGENT,
    def: 'A standard for connecting AI agents to local files, databases, and APIs — grounding the model in your actual codebase/data rather than a generic guess.',
    wiki: 'wiki/concepts/Claude Code CLI.md' },
  { term: 'Prompt Injection', cat: CAT.AGENT,
    def: 'Malicious instructions hidden in content the agent reads (web pages, files) that try to hijack its actions. Claude Code scans tool outputs for such instructions as a defense layer.',
    wiki: 'wiki/concepts/Claude Code CLI.md' },
  { term: 'Context Rot', cat: CAT.AGENT,
    def: 'Hallucinations and broken patterns caused by stale or poorly-managed context (wrong files, old summaries, conflicting instructions). Mitigated by a good CLAUDE.md and regular /compact.',
    wiki: 'wiki/concepts/Vibe Coding.md' },
  { term: 'Subagents', cat: CAT.AGENT,
    def: 'Specialized worker agents spawned to handle parallel tasks — e.g. one searches docs while another refactors and a third runs tests.',
    wiki: 'wiki/concepts/Claude Code CLI.md' },

  /* ── Finance · Quant Risk & Derivatives (from fin-quant-risk knowledge base) ── */
  { term: 'Front Office', cat: CAT.RISK,
    def: 'The revenue-generating division of a financial institution — traders and dealers who take market positions. Produces raw trade data for the middle and back office.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'Middle Office', cat: CAT.RISK,
    def: 'Monitors and quantifies firm-wide risk. Houses <strong>quants</strong> who build VaR, CVA, and volatility models. Responsible for backtesting — comparing forecasted VaR against realised P&L.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'Back Office', cat: CAT.RISK,
    def: 'Handles contract verification, cash settlement, system reconciliation, and daily P&L sign-off. The operational backbone of a financial institution.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'Backtesting', cat: CAT.RISK,
    def: 'The daily process of comparing yesterday\'s <strong>VaR forecast</strong> against today\'s confirmed P&L to validate a risk model\'s accuracy. If the model consistently under-predicts losses, quants must recalibrate.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'Mark-to-Market P&L', full: 'MTM — Unrealised Gain/Loss', cat: CAT.RISK,
    def: 'Open positions re-valued at current market prices daily. A large negative MTM triggers a <strong>margin call</strong>. Distinct from Realised P&L, which is locked in on settlement.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'Short Selling', cat: CAT.TRADE,
    def: 'Borrowing an asset and selling it immediately, expecting to buy it back cheaper later. Profit if price falls; <strong>theoretically unlimited loss</strong> if price rises. The seller must also compensate the lender for dividends/interest during the hold.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'Margin Call', cat: CAT.RISK,
    def: 'A demand for additional collateral when a position\'s unrealised losses exceed a threshold. Failure to meet a margin call triggers forced liquidation.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'Credit Spread', cat: CAT.RISK,
    def: 'The yield premium a risky bond pays above the risk-free rate, compensating investors for default risk. Widens as perceived creditworthiness deteriorates.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'Implied Volatility', full: 'IV', cat: CAT.RISK,
    def: 'Volatility back-calculated from current option market prices — the market\'s forward-looking estimate of future price uncertainty. Distinct from <strong>Historical Volatility</strong> which uses past data.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'GARCH', full: 'Generalised Autoregressive Conditional Heteroskedasticity', cat: CAT.RISK,
    def: 'A time-series model capturing <strong>volatility clustering</strong>: rough markets tend to stay rough. Formula σ²_t = ω + α·u²_(t-1) + β·σ²_(t-1) feeds yesterday\'s shock and variance forward.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'EWMA', full: 'Exponentially Weighted Moving Average', cat: CAT.RISK,
    def: 'A weighting scheme that gives more weight to recent observations when estimating volatility. More responsive to market regime changes than a simple rolling average.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'Modified Duration', cat: CAT.RISK,
    def: 'A bond\'s first-order price sensitivity to a 1% change in yield: ΔP ≈ −D_mod × P × Δy. Underestimates price change for large rate moves (that\'s what <strong>Convexity</strong> corrects).',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'Convexity', cat: CAT.RISK,
    def: 'The second-order (curvature) correction to bond price changes: ½ × C × P × (Δy)². Higher convexity is beneficial — the bond outperforms duration-only estimates whether rates rise or fall.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'Black-Scholes', cat: CAT.RISK,
    def: 'The seminal option pricing model: C = S·N(d₁) − K·e^(−rT)·N(d₂). Assumes continuous hedging, constant volatility, and log-normal returns. Basis for <strong>the Greeks</strong> (Delta, Gamma, Vega, Theta, Rho).',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'Delta (Δ)', full: 'Delta — Options Greek', cat: CAT.RISK,
    def: 'Rate of change of an option\'s price per £1 move in the underlying asset. Delta = 0 after <strong>delta hedging</strong>. Between 0 and 1 for calls; −1 to 0 for puts.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'Gamma (Γ)', full: 'Gamma — Options Greek', cat: CAT.RISK,
    def: 'Rate of change of <strong>Delta</strong> — the acceleration of option price sensitivity. High Gamma means Delta shifts rapidly, requiring frequent rehedging.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'Vega (ν)', full: 'Vega — Options Greek', cat: CAT.RISK,
    def: 'Sensitivity of an option\'s price to a 1% change in <strong>implied volatility</strong>. Long options are long vega (benefit from rising IV); short options are short vega.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'XVA', full: 'X-Value Adjustments', cat: CAT.RISK,
    def: 'A family of pricing adjustments beyond fair value: CVA (counterparty default), DVA (own default), FVA (funding cost), MVA (margin cost), KVA (capital cost). Post-Lehman regulatory requirement.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'CDS', full: 'Credit Default Swap', cat: CAT.RISK,
    def: 'A bilateral contract where the protection buyer pays a periodic premium (the <strong>CDS spread</strong> in bps) and receives compensation if the reference entity defaults. Used to both hedge and speculate on credit risk.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'QT', full: 'Quantitative Tightening', cat: CAT.RISK,
    def: 'A central bank drains liquidity by selling bonds or letting them mature — the reverse of QE. Used to fight inflation; raises market interest rates.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'YCC', full: 'Yield Curve Control', cat: CAT.RISK,
    def: 'A central bank policy that sets an explicit target for a specific bond maturity and defends it with unlimited purchases. Used by the Bank of Japan to peg the 10-year JGB near 0% until 2024.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'Inverted Yield Curve', cat: CAT.RISK,
    def: 'Short-term interest rates exceed long-term rates — an abnormal state caused by aggressive central bank rate hikes. Historically a <strong>leading recession indicator</strong> (typically 6–24 months ahead).',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'Interest Rate Parity', cat: CAT.RISK,
    def: 'The theory that exchange rate movements reflect interest rate differentials: E[Δe] ≈ i_domestic − i_foreign. The basis for the <strong>carry trade</strong> — borrowing in low-rate currencies to invest in high-rate currencies.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },
  { term: 'Cash Settlement', full: '差金決済 (Sashikin Kessai)', cat: CAT.TRADE,
    def: 'Settlement method where only the <em>price difference</em> between the agreed and market price is exchanged — no physical delivery of the underlying. Pioneered at the Dojima Rice Exchange (Osaka, 1730), the world\'s first derivatives market.',
    wiki: 'wiki/concepts/Financial Quant Risk Management.md' },

];
